### ISSUE TITLE
Migrate other protocols to corresponding repositories

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#254]
Transition other protocols in separate repositories:

- [x] @plehegar Merge https://github.com/w3c/trace-context/pull/249 and close https://github.com/w3c/trace-context/issues/247
- [x] @plehegar Create 3 repositories:
    ```
    https://github.com/w3c/trace-context-amqp
    https://github.com/w3c/trace-context-binary
    https://github.com/w3c/trace-context-mqtt
    ```
- [x] @plehegar Transfer issue Additional Protocol Support https://github.com/w3c/trace-context/issues/35 to https://github.com/w3c/trace-context-protocols-registry/ 
- [x] @plehegar Transfer issue https://github.com/w3c/trace-context/issues/198 to https://github.com/w3c/trace-context-protocols-registry/ 
- [x] @plehegar Transfer issue Discuss Binary Format https://github.com/w3c/trace-context/issues/5 to https://github.com/w3c/trace-context-binary
- [x] @SergeyKanzhelev  Move PR https://github.com/w3c/trace-context/pull/215 to https://github.com/w3c/trace-context-binary
- [x] @SergeyKanzhelev  Move PR https://github.com/w3c/trace-context/pull/217 to https://github.com/w3c/trace-context-amqp 
- [x] @SergeyKanzhelev  Move PR https://github.com/w3c/trace-context/pull/245 to https://github.com/w3c/trace-context-mqtt

**Comment by plehegar** [comment]
https://w3c.github.io/trace-context-protocols-registry/ was updated for AMQP and binary. MQTT will have to be added when ready.

**Comment by SergeyKanzhelev** [comment]
Binary PR moved: https://github.com/w3c/trace-context-binary/pull/2

**Comment by SergeyKanzhelev** [comment]
AMQP: https://github.com/w3c/trace-context-amqp/pull/1

**Comment by SergeyKanzhelev** [comment]
MQTT: https://github.com/w3c/trace-context-mqtt/pull/1

**Comment by SergeyKanzhelev** [comment]
Transition is completed. Closing the issue
